Allow Silverstripe 6 installs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,11 +15,11 @@ on:
 
 
 jobs:
-  silverstripe_5_php81:
-    name: "Silverstripe 5.0 | PHP 8.1"
+  silverstripe_6_php82:
+    name: "Silverstripe 6.0 | PHP 8.3"
     runs-on: ubuntu-latest
     env:
-      php_version: 8.1
+      php_version: 8.3
       php_extensions: ctype, dom, fileinfo, hash, intl, mbstring, session, simplexml, tokenizer, xml, pdo, mysqli, gd, zip
     services:
       mysql:
@@ -34,7 +34,7 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Setup PHP Extension Cache
         id: cache-env
@@ -42,10 +42,10 @@ jobs:
         with:
           php-version: ${{ env.php_version }}
           extensions: ${{ env.php_extensions }}
-          key: php81-ext-cache-${{ hashFiles('.github/workflows/ci.yml') }}
+          key: php83-ext-cache-${{ hashFiles('.github/workflows/ci.yml') }}
 
       - name: Cache PHP Extensions
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: ${{ steps.cache-env.outputs.dir }}
           key: ${{ steps.cache-env.outputs.key }}
@@ -65,11 +65,11 @@ jobs:
         run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
 
       - name: Cache composer dependencies
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: ${{ steps.composer-cache.outputs.dir }}
-          key: ${{ runner.os }}-composer-ss5-php81-${{ hashFiles('**/composer.json') }}-${{ hashFiles('.github/workflows/ci.yml') }}
-          restore-keys: ${{ runner.os }}-composer-ss5-php81-
+          key: ${{ runner.os }}-composer-ss6-php82-${{ hashFiles('**/composer.json') }}-${{ hashFiles('.github/workflows/ci.yml') }}
+          restore-keys: ${{ runner.os }}-composer-ss6-php82-
 
       - name: Install Composer dependencies
         env:
@@ -80,7 +80,8 @@ jobs:
           composer config allow-plugins.composer/installers true
           composer config allow-plugins.silverstripe/recipe-plugin true
           composer config allow-plugins.silverstripe/vendor-plugin true
-          composer require silverstripe/admin 2.0.* --no-update
+          composer require silverstripe/recipe-core 6.0.*
+          composer require silverstripe/login-forms 6.0.*
           composer install --verbose --no-interaction --no-progress --no-suggest --optimize-autoloader --ansi
 
       - name: Configure Environment
@@ -88,10 +89,95 @@ jobs:
           cp tests/utils/actions.env.template .env
           mkdir artifacts
 
+      - name: Configure matchers
+        uses: mheap/phpunit-matcher-action@v1
+
       - name: Perform PHPUnit Tests
         env:
           SS_DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
-        run: vendor/bin/phpunit --colors=always --printer WebbuildersGroup\\RememberMyAccount\\Tests\\PHPUnit\\Bootstrap\\GitHubActionsAnnotatorPrinter
+        run: SS_PHPUNIT_FLUSH=1 vendor/bin/phpunit --colors=always --teamcity
+
+  silverstripe_54_php82:
+    name: "Silverstripe 5.4 | PHP 8.2"
+    runs-on: ubuntu-latest
+    env:
+      php_version: 8.2
+      php_extensions: ctype, dom, fileinfo, hash, intl, mbstring, session, simplexml, tokenizer, xml, pdo, mysqli, gd, zip
+    services:
+      mysql:
+        image: mysql:8.0
+        env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
+          MYSQL_ROOT_PASSWORD: testpassword
+          MYSQL_DATABASE: test_db
+        ports:
+          - 3306/tcp
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup PHP Extension Cache
+        id: cache-env
+        uses: shivammathur/cache-extensions@v1
+        with:
+          php-version: ${{ env.php_version }}
+          extensions: ${{ env.php_extensions }}
+          key: php82-ext-cache-${{ hashFiles('.github/workflows/ci.yml') }}
+
+      - name: Cache PHP Extensions
+        uses: actions/cache@v4
+        with:
+          path: ${{ steps.cache-env.outputs.dir }}
+          key: ${{ steps.cache-env.outputs.key }}
+          restore-keys: ${{ steps.cache-env.outputs.key }}
+
+      - name: Setup PHP, with composer and extensions
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: ${{ env.php_version }}
+          extensions: ${{ env.php_extensions }}
+          ini-values: log_errors=On, error_log="${{github.workspace}}/artifacts/php_errors.log"
+          coverage: none
+          tools: composer:v2
+
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+
+      - name: Cache composer dependencies
+        uses: actions/cache@v4
+        with:
+          path: ${{ steps.composer-cache.outputs.dir }}
+          key: ${{ runner.os }}-composer-ss52-php82-${{ hashFiles('**/composer.json') }}-${{ hashFiles('.github/workflows/ci.yml') }}
+          restore-keys: ${{ runner.os }}-composer-ss52-php82-
+
+      - name: Install Composer dependencies
+        env:
+            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          composer self-update --ansi || true
+          if [[ $GITHUB_ACCESS_TOKEN ]]; then composer config --ansi -g github-oauth.github.com $GITHUB_ACCESS_TOKEN; fi
+          composer config allow-plugins.composer/installers true
+          composer config allow-plugins.silverstripe/recipe-plugin true
+          composer config allow-plugins.silverstripe/vendor-plugin true
+          composer require silverstripe/recipe-core 5.4.*
+          composer require silverstripe/login-forms 5.4.*
+          composer install --verbose --no-interaction --no-progress --no-suggest --optimize-autoloader --ansi
+
+      - name: Configure Environment
+        run: |
+          cp tests/utils/actions.env.template .env
+          mkdir artifacts
+
+      - name: Configure matchers
+        uses: mheap/phpunit-matcher-action@v1
+
+      - name: Perform PHPUnit Tests
+        env:
+          SS_DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
+        run: SS_PHPUNIT_FLUSH=1 vendor/bin/phpunit --colors=always --teamcity
 
   silverstripe_413_php80:
     name: "Silverstripe 4.13 | PHP 8.0"
@@ -158,7 +244,8 @@ jobs:
           composer config allow-plugins.composer/installers true
           composer config allow-plugins.silverstripe/recipe-plugin true
           composer config allow-plugins.silverstripe/vendor-plugin true
-          composer require silverstripe/admin 1.13.* --no-update
+          composer require silverstripe/recipe-core 4.4.*
+          composer require silverstripe/login-forms 4.0.*
           composer install --verbose --no-interaction --no-progress --no-suggest --optimize-autoloader --ansi
 
       - name: Configure Environment
@@ -169,82 +256,7 @@ jobs:
       - name: Perform PHPUnit Tests
         env:
           SS_DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
-        run: vendor/bin/phpunit --colors=always --printer WebbuildersGroup\\RememberMyAccount\\Tests\\PHPUnit\\Bootstrap\\GitHubActionsAnnotatorPrinter
-
-  silverstripe_413_php74:
-    name: "Silverstripe 4.13 | PHP 7.4"
-    runs-on: ubuntu-latest
-    env:
-      php_version: 7.4
-      php_extensions: ctype, dom, fileinfo, hash, intl, mbstring, session, simplexml, tokenizer, xml, pdo, mysqli, gd, zip
-    services:
-      mysql:
-        image: mysql:5.7
-        env:
-          MYSQL_ALLOW_EMPTY_PASSWORD: false
-          MYSQL_ROOT_PASSWORD: testpassword
-          MYSQL_DATABASE: test_db
-        ports:
-          - 3306/tcp
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: Setup PHP Extension Cache
-        id: cache-env
-        uses: shivammathur/cache-extensions@v1
-        with:
-          php-version: ${{ env.php_version }}
-          extensions: ${{ env.php_extensions }}
-          key: php74-ext-cache-${{ hashFiles('.github/workflows/ci.yml') }}
-
-      - name: Cache PHP Extensions
-        uses: actions/cache@v3
-        with:
-          path: ${{ steps.cache-env.outputs.dir }}
-          key: ${{ steps.cache-env.outputs.key }}
-          restore-keys: ${{ steps.cache-env.outputs.key }}
-
-      - name: Setup PHP, with composer and extensions
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ env.php_version }}
-          extensions: ${{ env.php_extensions }}
-          ini-values: log_errors=On, error_log="${{github.workspace}}/artifacts/php_errors.log"
-          coverage: none
-          tools: composer:v1
-
-      - name: Get composer cache directory
-        id: composer-cache
-        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
-
-      - name: Cache composer dependencies
-        uses: actions/cache@v3
-        with:
-          path: ${{ steps.composer-cache.outputs.dir }}
-          key: ${{ runner.os }}-composer-ss413-php74-${{ hashFiles('**/composer.json') }}-${{ hashFiles('.github/workflows/ci.yml') }}
-          restore-keys: ${{ runner.os }}-composer-ss413-php74-
-
-      - name: Install Composer dependencies
-        env:
-            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          composer self-update --ansi || true
-          if [[ $GITHUB_ACCESS_TOKEN ]]; then composer config --ansi -g github-oauth.github.com $GITHUB_ACCESS_TOKEN; fi
-          composer require silverstripe/admin 1.13.* --no-update
-          composer install --verbose --no-interaction --no-progress --no-suggest --optimize-autoloader --ansi
-
-      - name: Configure Environment
-        run: |
-          cp tests/utils/actions.env.template .env
-          mkdir artifacts
-
-      - name: Perform PHPUnit Tests
-        env:
-          SS_DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
-        run: vendor/bin/phpunit --colors=always --printer WebbuildersGroup\\RememberMyAccount\\Tests\\PHPUnit\\Bootstrap\\GitHubActionsAnnotatorPrinter
+        run: SS_PHPUNIT_FLUSH=1 vendor/bin/phpunit --colors=always --teamcity
 
   phpcs:
     name: "PHP_CodeSniffer"
